[general]
import = ["~/.config/alacritty/themes/themes/solarized_light.toml"]

[window]
startup_mode = "Maximized"

[font]
normal = { family = "HackGen35 Console NF", style = "Regular"}
size = 13
offset = { x = 1,y = 1 }

[terminal]
shell = { program = "/bin/zsh", args = ["-l", "-c", "tmux a -t 0 || tmux"]}
